package salesapp.roommybatis.mapper;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import salesapp.roommybatis.entity.PRoom;

public interface PRoomMapper {
    @Delete({
        "delete from p_Room",
        "where RoomGUID = #{roomguid,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String roomguid);

    @Insert({
        "insert into p_Room (RoomGUID, BUGUID, ",
        "ProjGUID, BldGUID, MainRoomGUID, ",
        "Unit, Floor, No, ",
        "Room, RoomCode, ",
        "HuXing, Status, ",
        "IsVirtualRoom, BldArea, ",
        "TnArea, BlRhDate, ",
        "RHBLZT, YFBZ, XPos, ",
        "YPos, ZxBz, Price, ",
        "TnPrice, Total, ",
        "ZxPrice, ZxTotal, ",
        "IsTempletRoom, Locker, ",
        "LockTime, TfDate, ",
        "DjArea, IsAreaModify, ",
        "VirtualStatus, RHDate, ",
        "JFRQ, XkRow, XkCol, ",
        "AreaStatus, West, ",
        "AreaChangingGUID, ImportDate, ",
        "ChooseRoom, CstName, ",
        "CstGUIDList, ChooseRoomCstName, ",
        "ChooseRoomDate, Jbr, ",
        "isAnnexe, Sight, ",
        "RoomStru, AbsolutelyFloor, ",
        "StatusChgGUID, SaleRentable, ",
        "RentPrice, CalcRentMode, ",
        "RentUnit, Bz, RentStatus, ",
        "ContinueRentStatus, NextRentStatus, ",
        "RentName, RentGUIDList, ",
        "RentStatusChgGUID, RentLocker, ",
        "RentLockTime, RentAmount, ",
        "BProductTypeCode, YsBldArea, ",
        "YsTnArea, ScBldArea, ",
        "ScTnArea, ChooseRoomNo, ",
        "ImportData_SP5, FloorNo, ",
        "UnitNo, SLControlDate, ",
        "IsHfLock, PriceDj, ",
        "TnPriceDj, TotalDj, ",
        "IsDj2AreaLock, IsBzj2AreaLock, ",
        "IsDjTf, IsBzjTf, ",
        "IsDjAreaModify, ChooseRoomBookingGUID, ",
        "Visible, isyl, roombz, ",
        "PreRoomGUID, FloorGUID, ",
        "UnitGUID, ResourcesTypeGUID, ",
        "CurRentStatus, RoomStatus, ",
        "Cg, Hz, Power, ",
        "Gas, Gs, Ps, ",
        "Kt, Other, YJQYDate, ",
        "CreateDate, IsAlowIn, ",
        "Client, EntrustDate, ",
        "EntrustJbr, EntrustJbDate, ",
        "EntrustEndDate, Contact, ",
        "EntrustJbrGUID, RoomInfo, ",
        "RoomShortInfo, RoomSort, ",
        "RoomZlBz, ERPCode, ",
        "IsTransferERPCode, ERPCodeApproveState, ",
        "VirtualAccount, SaleStatus, ",
        "ShortUnitNo, ShortVirtualAccount, ",
        "RoomMemo, JFMemo, ",
        "ReturnMsg)",
        "values (#{roomguid,jdbcType=CHAR}, #{buguid,jdbcType=CHAR}, ",
        "#{projguid,jdbcType=CHAR}, #{bldguid,jdbcType=CHAR}, #{mainroomguid,jdbcType=CHAR}, ",
        "#{unit,jdbcType=VARCHAR}, #{floor,jdbcType=VARCHAR}, #{no,jdbcType=VARCHAR}, ",
        "#{room,jdbcType=VARCHAR}, #{roomcode,jdbcType=VARCHAR}, ",
        "#{huxing,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, ",
        "#{isvirtualroom,jdbcType=TINYINT}, #{bldarea,jdbcType=DECIMAL}, ",
        "#{tnarea,jdbcType=DECIMAL}, #{blrhdate,jdbcType=TIMESTAMP}, ",
        "#{rhblzt,jdbcType=VARCHAR}, #{yfbz,jdbcType=VARCHAR}, #{xpos,jdbcType=INTEGER}, ",
        "#{ypos,jdbcType=INTEGER}, #{zxbz,jdbcType=VARCHAR}, #{price,jdbcType=DECIMAL}, ",
        "#{tnprice,jdbcType=DECIMAL}, #{total,jdbcType=DECIMAL}, ",
        "#{zxprice,jdbcType=DECIMAL}, #{zxtotal,jdbcType=DECIMAL}, ",
        "#{istempletroom,jdbcType=TINYINT}, #{locker,jdbcType=VARCHAR}, ",
        "#{locktime,jdbcType=TIMESTAMP}, #{tfdate,jdbcType=TIMESTAMP}, ",
        "#{djarea,jdbcType=VARCHAR}, #{isareamodify,jdbcType=TINYINT}, ",
        "#{virtualstatus,jdbcType=VARCHAR}, #{rhdate,jdbcType=TIMESTAMP}, ",
        "#{jfrq,jdbcType=TIMESTAMP}, #{xkrow,jdbcType=VARCHAR}, #{xkcol,jdbcType=VARCHAR}, ",
        "#{areastatus,jdbcType=VARCHAR}, #{west,jdbcType=VARCHAR}, ",
        "#{areachangingguid,jdbcType=CHAR}, #{importdate,jdbcType=TIMESTAMP}, ",
        "#{chooseroom,jdbcType=TINYINT}, #{cstname,jdbcType=VARCHAR}, ",
        "#{cstguidlist,jdbcType=VARCHAR}, #{chooseroomcstname,jdbcType=VARCHAR}, ",
        "#{chooseroomdate,jdbcType=TIMESTAMP}, #{jbr,jdbcType=VARCHAR}, ",
        "#{isannexe,jdbcType=TINYINT}, #{sight,jdbcType=VARCHAR}, ",
        "#{roomstru,jdbcType=VARCHAR}, #{absolutelyfloor,jdbcType=VARCHAR}, ",
        "#{statuschgguid,jdbcType=CHAR}, #{salerentable,jdbcType=VARCHAR}, ",
        "#{rentprice,jdbcType=DECIMAL}, #{calcrentmode,jdbcType=VARCHAR}, ",
        "#{rentunit,jdbcType=VARCHAR}, #{bz,jdbcType=VARCHAR}, #{rentstatus,jdbcType=VARCHAR}, ",
        "#{continuerentstatus,jdbcType=VARCHAR}, #{nextrentstatus,jdbcType=VARCHAR}, ",
        "#{rentname,jdbcType=VARCHAR}, #{rentguidlist,jdbcType=VARCHAR}, ",
        "#{rentstatuschgguid,jdbcType=CHAR}, #{rentlocker,jdbcType=VARCHAR}, ",
        "#{rentlocktime,jdbcType=TIMESTAMP}, #{rentamount,jdbcType=DECIMAL}, ",
        "#{bproducttypecode,jdbcType=VARCHAR}, #{ysbldarea,jdbcType=DECIMAL}, ",
        "#{ystnarea,jdbcType=DECIMAL}, #{scbldarea,jdbcType=DECIMAL}, ",
        "#{sctnarea,jdbcType=DECIMAL}, #{chooseroomno,jdbcType=INTEGER}, ",
        "#{importdataSp5,jdbcType=VARCHAR}, #{floorno,jdbcType=INTEGER}, ",
        "#{unitno,jdbcType=INTEGER}, #{slcontroldate,jdbcType=TIMESTAMP}, ",
        "#{ishflock,jdbcType=TINYINT}, #{pricedj,jdbcType=DECIMAL}, ",
        "#{tnpricedj,jdbcType=DECIMAL}, #{totaldj,jdbcType=DECIMAL}, ",
        "#{isdj2arealock,jdbcType=TINYINT}, #{isbzj2arealock,jdbcType=TINYINT}, ",
        "#{isdjtf,jdbcType=TINYINT}, #{isbzjtf,jdbcType=TINYINT}, ",
        "#{isdjareamodify,jdbcType=TINYINT}, #{chooseroombookingguid,jdbcType=CHAR}, ",
        "#{visible,jdbcType=INTEGER}, #{isyl,jdbcType=INTEGER}, #{roombz,jdbcType=VARCHAR}, ",
        "#{preroomguid,jdbcType=VARCHAR}, #{floorguid,jdbcType=CHAR}, ",
        "#{unitguid,jdbcType=CHAR}, #{resourcestypeguid,jdbcType=CHAR}, ",
        "#{currentstatus,jdbcType=TINYINT}, #{roomstatus,jdbcType=TINYINT}, ",
        "#{cg,jdbcType=VARCHAR}, #{hz,jdbcType=VARCHAR}, #{power,jdbcType=VARCHAR}, ",
        "#{gas,jdbcType=VARCHAR}, #{gs,jdbcType=VARCHAR}, #{ps,jdbcType=VARCHAR}, ",
        "#{kt,jdbcType=VARCHAR}, #{other,jdbcType=VARCHAR}, #{yjqydate,jdbcType=TIMESTAMP}, ",
        "#{createdate,jdbcType=TIMESTAMP}, #{isalowin,jdbcType=TINYINT}, ",
        "#{client,jdbcType=VARCHAR}, #{entrustdate,jdbcType=TIMESTAMP}, ",
        "#{entrustjbr,jdbcType=VARCHAR}, #{entrustjbdate,jdbcType=TIMESTAMP}, ",
        "#{entrustenddate,jdbcType=TIMESTAMP}, #{contact,jdbcType=VARCHAR}, ",
        "#{entrustjbrguid,jdbcType=CHAR}, #{roominfo,jdbcType=VARCHAR}, ",
        "#{roomshortinfo,jdbcType=VARCHAR}, #{roomsort,jdbcType=VARCHAR}, ",
        "#{roomzlbz,jdbcType=VARCHAR}, #{erpcode,jdbcType=VARCHAR}, ",
        "#{istransfererpcode,jdbcType=TINYINT}, #{erpcodeapprovestate,jdbcType=VARCHAR}, ",
        "#{virtualaccount,jdbcType=VARCHAR}, #{salestatus,jdbcType=VARCHAR}, ",
        "#{shortunitno,jdbcType=VARCHAR}, #{shortvirtualaccount,jdbcType=VARCHAR}, ",
        "#{roommemo,jdbcType=LONGVARCHAR}, #{jfmemo,jdbcType=LONGVARCHAR}, ",
        "#{returnmsg,jdbcType=LONGVARCHAR})"
    })
    int insert(PRoom record);

    @InsertProvider(type=PRoomSqlProvider.class, method="insertSelective")
    int insertSelective(PRoom record);

    @Select({
        "select",
        "RoomGUID, BUGUID, ProjGUID, BldGUID, MainRoomGUID, Unit, Floor, No, Room, RoomCode, ",
        "HuXing, Status, IsVirtualRoom, BldArea, TnArea, BlRhDate, RHBLZT, YFBZ, XPos, ",
        "YPos, ZxBz, Price, TnPrice, Total, ZxPrice, ZxTotal, IsTempletRoom, Locker, ",
        "LockTime, TfDate, DjArea, IsAreaModify, VirtualStatus, RHDate, JFRQ, XkRow, ",
        "XkCol, AreaStatus, West, AreaChangingGUID, ImportDate, ChooseRoom, CstName, ",
        "CstGUIDList, ChooseRoomCstName, ChooseRoomDate, Jbr, isAnnexe, Sight, RoomStru, ",
        "AbsolutelyFloor, StatusChgGUID, SaleRentable, RentPrice, CalcRentMode, RentUnit, ",
        "Bz, RentStatus, ContinueRentStatus, NextRentStatus, RentName, RentGUIDList, ",
        "RentStatusChgGUID, RentLocker, RentLockTime, RentAmount, BProductTypeCode, YsBldArea, ",
        "YsTnArea, ScBldArea, ScTnArea, ChooseRoomNo, ImportData_SP5, FloorNo, UnitNo, ",
        "SLControlDate, IsHfLock, PriceDj, TnPriceDj, TotalDj, IsDj2AreaLock, IsBzj2AreaLock, ",
        "IsDjTf, IsBzjTf, IsDjAreaModify, ChooseRoomBookingGUID, Visible, isyl, roombz, ",
        "PreRoomGUID, FloorGUID, UnitGUID, ResourcesTypeGUID, CurRentStatus, RoomStatus, ",
        "Cg, Hz, Power, Gas, Gs, Ps, Kt, Other, YJQYDate, CreateDate, IsAlowIn, Client, ",
        "EntrustDate, EntrustJbr, EntrustJbDate, EntrustEndDate, Contact, EntrustJbrGUID, ",
        "RoomInfo, RoomShortInfo, RoomSort, RoomZlBz, ERPCode, IsTransferERPCode, ERPCodeApproveState, ",
        "VirtualAccount, SaleStatus, ShortUnitNo, ShortVirtualAccount, RoomMemo, JFMemo, ",
        "ReturnMsg",
        "from p_Room",
        "where RoomGUID = #{roomguid,jdbcType=CHAR}"
    })
    @Results({
        @Result(column="RoomGUID", property="roomguid", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="BUGUID", property="buguid", jdbcType=JdbcType.CHAR),
        @Result(column="ProjGUID", property="projguid", jdbcType=JdbcType.CHAR),
        @Result(column="BldGUID", property="bldguid", jdbcType=JdbcType.CHAR),
        @Result(column="MainRoomGUID", property="mainroomguid", jdbcType=JdbcType.CHAR),
        @Result(column="Unit", property="unit", jdbcType=JdbcType.VARCHAR),
        @Result(column="Floor", property="floor", jdbcType=JdbcType.VARCHAR),
        @Result(column="No", property="no", jdbcType=JdbcType.VARCHAR),
        @Result(column="Room", property="room", jdbcType=JdbcType.VARCHAR),
        @Result(column="RoomCode", property="roomcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="HuXing", property="huxing", jdbcType=JdbcType.VARCHAR),
        @Result(column="Status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="IsVirtualRoom", property="isvirtualroom", jdbcType=JdbcType.TINYINT),
        @Result(column="BldArea", property="bldarea", jdbcType=JdbcType.DECIMAL),
        @Result(column="TnArea", property="tnarea", jdbcType=JdbcType.DECIMAL),
        @Result(column="BlRhDate", property="blrhdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RHBLZT", property="rhblzt", jdbcType=JdbcType.VARCHAR),
        @Result(column="YFBZ", property="yfbz", jdbcType=JdbcType.VARCHAR),
        @Result(column="XPos", property="xpos", jdbcType=JdbcType.INTEGER),
        @Result(column="YPos", property="ypos", jdbcType=JdbcType.INTEGER),
        @Result(column="ZxBz", property="zxbz", jdbcType=JdbcType.VARCHAR),
        @Result(column="Price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="TnPrice", property="tnprice", jdbcType=JdbcType.DECIMAL),
        @Result(column="Total", property="total", jdbcType=JdbcType.DECIMAL),
        @Result(column="ZxPrice", property="zxprice", jdbcType=JdbcType.DECIMAL),
        @Result(column="ZxTotal", property="zxtotal", jdbcType=JdbcType.DECIMAL),
        @Result(column="IsTempletRoom", property="istempletroom", jdbcType=JdbcType.TINYINT),
        @Result(column="Locker", property="locker", jdbcType=JdbcType.VARCHAR),
        @Result(column="LockTime", property="locktime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="TfDate", property="tfdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DjArea", property="djarea", jdbcType=JdbcType.VARCHAR),
        @Result(column="IsAreaModify", property="isareamodify", jdbcType=JdbcType.TINYINT),
        @Result(column="VirtualStatus", property="virtualstatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="RHDate", property="rhdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="JFRQ", property="jfrq", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="XkRow", property="xkrow", jdbcType=JdbcType.VARCHAR),
        @Result(column="XkCol", property="xkcol", jdbcType=JdbcType.VARCHAR),
        @Result(column="AreaStatus", property="areastatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="West", property="west", jdbcType=JdbcType.VARCHAR),
        @Result(column="AreaChangingGUID", property="areachangingguid", jdbcType=JdbcType.CHAR),
        @Result(column="ImportDate", property="importdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="ChooseRoom", property="chooseroom", jdbcType=JdbcType.TINYINT),
        @Result(column="CstName", property="cstname", jdbcType=JdbcType.VARCHAR),
        @Result(column="CstGUIDList", property="cstguidlist", jdbcType=JdbcType.VARCHAR),
        @Result(column="ChooseRoomCstName", property="chooseroomcstname", jdbcType=JdbcType.VARCHAR),
        @Result(column="ChooseRoomDate", property="chooseroomdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="Jbr", property="jbr", jdbcType=JdbcType.VARCHAR),
        @Result(column="isAnnexe", property="isannexe", jdbcType=JdbcType.TINYINT),
        @Result(column="Sight", property="sight", jdbcType=JdbcType.VARCHAR),
        @Result(column="RoomStru", property="roomstru", jdbcType=JdbcType.VARCHAR),
        @Result(column="AbsolutelyFloor", property="absolutelyfloor", jdbcType=JdbcType.VARCHAR),
        @Result(column="StatusChgGUID", property="statuschgguid", jdbcType=JdbcType.CHAR),
        @Result(column="SaleRentable", property="salerentable", jdbcType=JdbcType.VARCHAR),
        @Result(column="RentPrice", property="rentprice", jdbcType=JdbcType.DECIMAL),
        @Result(column="CalcRentMode", property="calcrentmode", jdbcType=JdbcType.VARCHAR),
        @Result(column="RentUnit", property="rentunit", jdbcType=JdbcType.VARCHAR),
        @Result(column="Bz", property="bz", jdbcType=JdbcType.VARCHAR),
        @Result(column="RentStatus", property="rentstatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="ContinueRentStatus", property="continuerentstatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="NextRentStatus", property="nextrentstatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="RentName", property="rentname", jdbcType=JdbcType.VARCHAR),
        @Result(column="RentGUIDList", property="rentguidlist", jdbcType=JdbcType.VARCHAR),
        @Result(column="RentStatusChgGUID", property="rentstatuschgguid", jdbcType=JdbcType.CHAR),
        @Result(column="RentLocker", property="rentlocker", jdbcType=JdbcType.VARCHAR),
        @Result(column="RentLockTime", property="rentlocktime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RentAmount", property="rentamount", jdbcType=JdbcType.DECIMAL),
        @Result(column="BProductTypeCode", property="bproducttypecode", jdbcType=JdbcType.VARCHAR),
        @Result(column="YsBldArea", property="ysbldarea", jdbcType=JdbcType.DECIMAL),
        @Result(column="YsTnArea", property="ystnarea", jdbcType=JdbcType.DECIMAL),
        @Result(column="ScBldArea", property="scbldarea", jdbcType=JdbcType.DECIMAL),
        @Result(column="ScTnArea", property="sctnarea", jdbcType=JdbcType.DECIMAL),
        @Result(column="ChooseRoomNo", property="chooseroomno", jdbcType=JdbcType.INTEGER),
        @Result(column="ImportData_SP5", property="importdataSp5", jdbcType=JdbcType.VARCHAR),
        @Result(column="FloorNo", property="floorno", jdbcType=JdbcType.INTEGER),
        @Result(column="UnitNo", property="unitno", jdbcType=JdbcType.INTEGER),
        @Result(column="SLControlDate", property="slcontroldate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="IsHfLock", property="ishflock", jdbcType=JdbcType.TINYINT),
        @Result(column="PriceDj", property="pricedj", jdbcType=JdbcType.DECIMAL),
        @Result(column="TnPriceDj", property="tnpricedj", jdbcType=JdbcType.DECIMAL),
        @Result(column="TotalDj", property="totaldj", jdbcType=JdbcType.DECIMAL),
        @Result(column="IsDj2AreaLock", property="isdj2arealock", jdbcType=JdbcType.TINYINT),
        @Result(column="IsBzj2AreaLock", property="isbzj2arealock", jdbcType=JdbcType.TINYINT),
        @Result(column="IsDjTf", property="isdjtf", jdbcType=JdbcType.TINYINT),
        @Result(column="IsBzjTf", property="isbzjtf", jdbcType=JdbcType.TINYINT),
        @Result(column="IsDjAreaModify", property="isdjareamodify", jdbcType=JdbcType.TINYINT),
        @Result(column="ChooseRoomBookingGUID", property="chooseroombookingguid", jdbcType=JdbcType.CHAR),
        @Result(column="Visible", property="visible", jdbcType=JdbcType.INTEGER),
        @Result(column="isyl", property="isyl", jdbcType=JdbcType.INTEGER),
        @Result(column="roombz", property="roombz", jdbcType=JdbcType.VARCHAR),
        @Result(column="PreRoomGUID", property="preroomguid", jdbcType=JdbcType.VARCHAR),
        @Result(column="FloorGUID", property="floorguid", jdbcType=JdbcType.CHAR),
        @Result(column="UnitGUID", property="unitguid", jdbcType=JdbcType.CHAR),
        @Result(column="ResourcesTypeGUID", property="resourcestypeguid", jdbcType=JdbcType.CHAR),
        @Result(column="CurRentStatus", property="currentstatus", jdbcType=JdbcType.TINYINT),
        @Result(column="RoomStatus", property="roomstatus", jdbcType=JdbcType.TINYINT),
        @Result(column="Cg", property="cg", jdbcType=JdbcType.VARCHAR),
        @Result(column="Hz", property="hz", jdbcType=JdbcType.VARCHAR),
        @Result(column="Power", property="power", jdbcType=JdbcType.VARCHAR),
        @Result(column="Gas", property="gas", jdbcType=JdbcType.VARCHAR),
        @Result(column="Gs", property="gs", jdbcType=JdbcType.VARCHAR),
        @Result(column="Ps", property="ps", jdbcType=JdbcType.VARCHAR),
        @Result(column="Kt", property="kt", jdbcType=JdbcType.VARCHAR),
        @Result(column="Other", property="other", jdbcType=JdbcType.VARCHAR),
        @Result(column="YJQYDate", property="yjqydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CreateDate", property="createdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="IsAlowIn", property="isalowin", jdbcType=JdbcType.TINYINT),
        @Result(column="Client", property="client", jdbcType=JdbcType.VARCHAR),
        @Result(column="EntrustDate", property="entrustdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="EntrustJbr", property="entrustjbr", jdbcType=JdbcType.VARCHAR),
        @Result(column="EntrustJbDate", property="entrustjbdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="EntrustEndDate", property="entrustenddate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="Contact", property="contact", jdbcType=JdbcType.VARCHAR),
        @Result(column="EntrustJbrGUID", property="entrustjbrguid", jdbcType=JdbcType.CHAR),
        @Result(column="RoomInfo", property="roominfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="RoomShortInfo", property="roomshortinfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="RoomSort", property="roomsort", jdbcType=JdbcType.VARCHAR),
        @Result(column="RoomZlBz", property="roomzlbz", jdbcType=JdbcType.VARCHAR),
        @Result(column="ERPCode", property="erpcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="IsTransferERPCode", property="istransfererpcode", jdbcType=JdbcType.TINYINT),
        @Result(column="ERPCodeApproveState", property="erpcodeapprovestate", jdbcType=JdbcType.VARCHAR),
        @Result(column="VirtualAccount", property="virtualaccount", jdbcType=JdbcType.VARCHAR),
        @Result(column="SaleStatus", property="salestatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="ShortUnitNo", property="shortunitno", jdbcType=JdbcType.VARCHAR),
        @Result(column="ShortVirtualAccount", property="shortvirtualaccount", jdbcType=JdbcType.VARCHAR),
        @Result(column="RoomMemo", property="roommemo", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="JFMemo", property="jfmemo", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="ReturnMsg", property="returnmsg", jdbcType=JdbcType.LONGVARCHAR)
    })
    PRoom selectByPrimaryKey(String roomguid);

    @UpdateProvider(type=PRoomSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PRoom record);

    @Update({
        "update p_Room",
        "set BUGUID = #{buguid,jdbcType=CHAR},",
          "ProjGUID = #{projguid,jdbcType=CHAR},",
          "BldGUID = #{bldguid,jdbcType=CHAR},",
          "MainRoomGUID = #{mainroomguid,jdbcType=CHAR},",
          "Unit = #{unit,jdbcType=VARCHAR},",
          "Floor = #{floor,jdbcType=VARCHAR},",
          "No = #{no,jdbcType=VARCHAR},",
          "Room = #{room,jdbcType=VARCHAR},",
          "RoomCode = #{roomcode,jdbcType=VARCHAR},",
          "HuXing = #{huxing,jdbcType=VARCHAR},",
          "Status = #{status,jdbcType=VARCHAR},",
          "IsVirtualRoom = #{isvirtualroom,jdbcType=TINYINT},",
          "BldArea = #{bldarea,jdbcType=DECIMAL},",
          "TnArea = #{tnarea,jdbcType=DECIMAL},",
          "BlRhDate = #{blrhdate,jdbcType=TIMESTAMP},",
          "RHBLZT = #{rhblzt,jdbcType=VARCHAR},",
          "YFBZ = #{yfbz,jdbcType=VARCHAR},",
          "XPos = #{xpos,jdbcType=INTEGER},",
          "YPos = #{ypos,jdbcType=INTEGER},",
          "ZxBz = #{zxbz,jdbcType=VARCHAR},",
          "Price = #{price,jdbcType=DECIMAL},",
          "TnPrice = #{tnprice,jdbcType=DECIMAL},",
          "Total = #{total,jdbcType=DECIMAL},",
          "ZxPrice = #{zxprice,jdbcType=DECIMAL},",
          "ZxTotal = #{zxtotal,jdbcType=DECIMAL},",
          "IsTempletRoom = #{istempletroom,jdbcType=TINYINT},",
          "Locker = #{locker,jdbcType=VARCHAR},",
          "LockTime = #{locktime,jdbcType=TIMESTAMP},",
          "TfDate = #{tfdate,jdbcType=TIMESTAMP},",
          "DjArea = #{djarea,jdbcType=VARCHAR},",
          "IsAreaModify = #{isareamodify,jdbcType=TINYINT},",
          "VirtualStatus = #{virtualstatus,jdbcType=VARCHAR},",
          "RHDate = #{rhdate,jdbcType=TIMESTAMP},",
          "JFRQ = #{jfrq,jdbcType=TIMESTAMP},",
          "XkRow = #{xkrow,jdbcType=VARCHAR},",
          "XkCol = #{xkcol,jdbcType=VARCHAR},",
          "AreaStatus = #{areastatus,jdbcType=VARCHAR},",
          "West = #{west,jdbcType=VARCHAR},",
          "AreaChangingGUID = #{areachangingguid,jdbcType=CHAR},",
          "ImportDate = #{importdate,jdbcType=TIMESTAMP},",
          "ChooseRoom = #{chooseroom,jdbcType=TINYINT},",
          "CstName = #{cstname,jdbcType=VARCHAR},",
          "CstGUIDList = #{cstguidlist,jdbcType=VARCHAR},",
          "ChooseRoomCstName = #{chooseroomcstname,jdbcType=VARCHAR},",
          "ChooseRoomDate = #{chooseroomdate,jdbcType=TIMESTAMP},",
          "Jbr = #{jbr,jdbcType=VARCHAR},",
          "isAnnexe = #{isannexe,jdbcType=TINYINT},",
          "Sight = #{sight,jdbcType=VARCHAR},",
          "RoomStru = #{roomstru,jdbcType=VARCHAR},",
          "AbsolutelyFloor = #{absolutelyfloor,jdbcType=VARCHAR},",
          "StatusChgGUID = #{statuschgguid,jdbcType=CHAR},",
          "SaleRentable = #{salerentable,jdbcType=VARCHAR},",
          "RentPrice = #{rentprice,jdbcType=DECIMAL},",
          "CalcRentMode = #{calcrentmode,jdbcType=VARCHAR},",
          "RentUnit = #{rentunit,jdbcType=VARCHAR},",
          "Bz = #{bz,jdbcType=VARCHAR},",
          "RentStatus = #{rentstatus,jdbcType=VARCHAR},",
          "ContinueRentStatus = #{continuerentstatus,jdbcType=VARCHAR},",
          "NextRentStatus = #{nextrentstatus,jdbcType=VARCHAR},",
          "RentName = #{rentname,jdbcType=VARCHAR},",
          "RentGUIDList = #{rentguidlist,jdbcType=VARCHAR},",
          "RentStatusChgGUID = #{rentstatuschgguid,jdbcType=CHAR},",
          "RentLocker = #{rentlocker,jdbcType=VARCHAR},",
          "RentLockTime = #{rentlocktime,jdbcType=TIMESTAMP},",
          "RentAmount = #{rentamount,jdbcType=DECIMAL},",
          "BProductTypeCode = #{bproducttypecode,jdbcType=VARCHAR},",
          "YsBldArea = #{ysbldarea,jdbcType=DECIMAL},",
          "YsTnArea = #{ystnarea,jdbcType=DECIMAL},",
          "ScBldArea = #{scbldarea,jdbcType=DECIMAL},",
          "ScTnArea = #{sctnarea,jdbcType=DECIMAL},",
          "ChooseRoomNo = #{chooseroomno,jdbcType=INTEGER},",
          "ImportData_SP5 = #{importdataSp5,jdbcType=VARCHAR},",
          "FloorNo = #{floorno,jdbcType=INTEGER},",
          "UnitNo = #{unitno,jdbcType=INTEGER},",
          "SLControlDate = #{slcontroldate,jdbcType=TIMESTAMP},",
          "IsHfLock = #{ishflock,jdbcType=TINYINT},",
          "PriceDj = #{pricedj,jdbcType=DECIMAL},",
          "TnPriceDj = #{tnpricedj,jdbcType=DECIMAL},",
          "TotalDj = #{totaldj,jdbcType=DECIMAL},",
          "IsDj2AreaLock = #{isdj2arealock,jdbcType=TINYINT},",
          "IsBzj2AreaLock = #{isbzj2arealock,jdbcType=TINYINT},",
          "IsDjTf = #{isdjtf,jdbcType=TINYINT},",
          "IsBzjTf = #{isbzjtf,jdbcType=TINYINT},",
          "IsDjAreaModify = #{isdjareamodify,jdbcType=TINYINT},",
          "ChooseRoomBookingGUID = #{chooseroombookingguid,jdbcType=CHAR},",
          "Visible = #{visible,jdbcType=INTEGER},",
          "isyl = #{isyl,jdbcType=INTEGER},",
          "roombz = #{roombz,jdbcType=VARCHAR},",
          "PreRoomGUID = #{preroomguid,jdbcType=VARCHAR},",
          "FloorGUID = #{floorguid,jdbcType=CHAR},",
          "UnitGUID = #{unitguid,jdbcType=CHAR},",
          "ResourcesTypeGUID = #{resourcestypeguid,jdbcType=CHAR},",
          "CurRentStatus = #{currentstatus,jdbcType=TINYINT},",
          "RoomStatus = #{roomstatus,jdbcType=TINYINT},",
          "Cg = #{cg,jdbcType=VARCHAR},",
          "Hz = #{hz,jdbcType=VARCHAR},",
          "Power = #{power,jdbcType=VARCHAR},",
          "Gas = #{gas,jdbcType=VARCHAR},",
          "Gs = #{gs,jdbcType=VARCHAR},",
          "Ps = #{ps,jdbcType=VARCHAR},",
          "Kt = #{kt,jdbcType=VARCHAR},",
          "Other = #{other,jdbcType=VARCHAR},",
          "YJQYDate = #{yjqydate,jdbcType=TIMESTAMP},",
          "CreateDate = #{createdate,jdbcType=TIMESTAMP},",
          "IsAlowIn = #{isalowin,jdbcType=TINYINT},",
          "Client = #{client,jdbcType=VARCHAR},",
          "EntrustDate = #{entrustdate,jdbcType=TIMESTAMP},",
          "EntrustJbr = #{entrustjbr,jdbcType=VARCHAR},",
          "EntrustJbDate = #{entrustjbdate,jdbcType=TIMESTAMP},",
          "EntrustEndDate = #{entrustenddate,jdbcType=TIMESTAMP},",
          "Contact = #{contact,jdbcType=VARCHAR},",
          "EntrustJbrGUID = #{entrustjbrguid,jdbcType=CHAR},",
          "RoomInfo = #{roominfo,jdbcType=VARCHAR},",
          "RoomShortInfo = #{roomshortinfo,jdbcType=VARCHAR},",
          "RoomSort = #{roomsort,jdbcType=VARCHAR},",
          "RoomZlBz = #{roomzlbz,jdbcType=VARCHAR},",
          "ERPCode = #{erpcode,jdbcType=VARCHAR},",
          "IsTransferERPCode = #{istransfererpcode,jdbcType=TINYINT},",
          "ERPCodeApproveState = #{erpcodeapprovestate,jdbcType=VARCHAR},",
          "VirtualAccount = #{virtualaccount,jdbcType=VARCHAR},",
          "SaleStatus = #{salestatus,jdbcType=VARCHAR},",
          "ShortUnitNo = #{shortunitno,jdbcType=VARCHAR},",
          "ShortVirtualAccount = #{shortvirtualaccount,jdbcType=VARCHAR},",
          "RoomMemo = #{roommemo,jdbcType=LONGVARCHAR},",
          "JFMemo = #{jfmemo,jdbcType=LONGVARCHAR},",
          "ReturnMsg = #{returnmsg,jdbcType=LONGVARCHAR}",
        "where RoomGUID = #{roomguid,jdbcType=CHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(PRoom record);

    @Update({
        "update p_Room",
        "set BUGUID = #{buguid,jdbcType=CHAR},",
          "ProjGUID = #{projguid,jdbcType=CHAR},",
          "BldGUID = #{bldguid,jdbcType=CHAR},",
          "MainRoomGUID = #{mainroomguid,jdbcType=CHAR},",
          "Unit = #{unit,jdbcType=VARCHAR},",
          "Floor = #{floor,jdbcType=VARCHAR},",
          "No = #{no,jdbcType=VARCHAR},",
          "Room = #{room,jdbcType=VARCHAR},",
          "RoomCode = #{roomcode,jdbcType=VARCHAR},",
          "HuXing = #{huxing,jdbcType=VARCHAR},",
          "Status = #{status,jdbcType=VARCHAR},",
          "IsVirtualRoom = #{isvirtualroom,jdbcType=TINYINT},",
          "BldArea = #{bldarea,jdbcType=DECIMAL},",
          "TnArea = #{tnarea,jdbcType=DECIMAL},",
          "BlRhDate = #{blrhdate,jdbcType=TIMESTAMP},",
          "RHBLZT = #{rhblzt,jdbcType=VARCHAR},",
          "YFBZ = #{yfbz,jdbcType=VARCHAR},",
          "XPos = #{xpos,jdbcType=INTEGER},",
          "YPos = #{ypos,jdbcType=INTEGER},",
          "ZxBz = #{zxbz,jdbcType=VARCHAR},",
          "Price = #{price,jdbcType=DECIMAL},",
          "TnPrice = #{tnprice,jdbcType=DECIMAL},",
          "Total = #{total,jdbcType=DECIMAL},",
          "ZxPrice = #{zxprice,jdbcType=DECIMAL},",
          "ZxTotal = #{zxtotal,jdbcType=DECIMAL},",
          "IsTempletRoom = #{istempletroom,jdbcType=TINYINT},",
          "Locker = #{locker,jdbcType=VARCHAR},",
          "LockTime = #{locktime,jdbcType=TIMESTAMP},",
          "TfDate = #{tfdate,jdbcType=TIMESTAMP},",
          "DjArea = #{djarea,jdbcType=VARCHAR},",
          "IsAreaModify = #{isareamodify,jdbcType=TINYINT},",
          "VirtualStatus = #{virtualstatus,jdbcType=VARCHAR},",
          "RHDate = #{rhdate,jdbcType=TIMESTAMP},",
          "JFRQ = #{jfrq,jdbcType=TIMESTAMP},",
          "XkRow = #{xkrow,jdbcType=VARCHAR},",
          "XkCol = #{xkcol,jdbcType=VARCHAR},",
          "AreaStatus = #{areastatus,jdbcType=VARCHAR},",
          "West = #{west,jdbcType=VARCHAR},",
          "AreaChangingGUID = #{areachangingguid,jdbcType=CHAR},",
          "ImportDate = #{importdate,jdbcType=TIMESTAMP},",
          "ChooseRoom = #{chooseroom,jdbcType=TINYINT},",
          "CstName = #{cstname,jdbcType=VARCHAR},",
          "CstGUIDList = #{cstguidlist,jdbcType=VARCHAR},",
          "ChooseRoomCstName = #{chooseroomcstname,jdbcType=VARCHAR},",
          "ChooseRoomDate = #{chooseroomdate,jdbcType=TIMESTAMP},",
          "Jbr = #{jbr,jdbcType=VARCHAR},",
          "isAnnexe = #{isannexe,jdbcType=TINYINT},",
          "Sight = #{sight,jdbcType=VARCHAR},",
          "RoomStru = #{roomstru,jdbcType=VARCHAR},",
          "AbsolutelyFloor = #{absolutelyfloor,jdbcType=VARCHAR},",
          "StatusChgGUID = #{statuschgguid,jdbcType=CHAR},",
          "SaleRentable = #{salerentable,jdbcType=VARCHAR},",
          "RentPrice = #{rentprice,jdbcType=DECIMAL},",
          "CalcRentMode = #{calcrentmode,jdbcType=VARCHAR},",
          "RentUnit = #{rentunit,jdbcType=VARCHAR},",
          "Bz = #{bz,jdbcType=VARCHAR},",
          "RentStatus = #{rentstatus,jdbcType=VARCHAR},",
          "ContinueRentStatus = #{continuerentstatus,jdbcType=VARCHAR},",
          "NextRentStatus = #{nextrentstatus,jdbcType=VARCHAR},",
          "RentName = #{rentname,jdbcType=VARCHAR},",
          "RentGUIDList = #{rentguidlist,jdbcType=VARCHAR},",
          "RentStatusChgGUID = #{rentstatuschgguid,jdbcType=CHAR},",
          "RentLocker = #{rentlocker,jdbcType=VARCHAR},",
          "RentLockTime = #{rentlocktime,jdbcType=TIMESTAMP},",
          "RentAmount = #{rentamount,jdbcType=DECIMAL},",
          "BProductTypeCode = #{bproducttypecode,jdbcType=VARCHAR},",
          "YsBldArea = #{ysbldarea,jdbcType=DECIMAL},",
          "YsTnArea = #{ystnarea,jdbcType=DECIMAL},",
          "ScBldArea = #{scbldarea,jdbcType=DECIMAL},",
          "ScTnArea = #{sctnarea,jdbcType=DECIMAL},",
          "ChooseRoomNo = #{chooseroomno,jdbcType=INTEGER},",
          "ImportData_SP5 = #{importdataSp5,jdbcType=VARCHAR},",
          "FloorNo = #{floorno,jdbcType=INTEGER},",
          "UnitNo = #{unitno,jdbcType=INTEGER},",
          "SLControlDate = #{slcontroldate,jdbcType=TIMESTAMP},",
          "IsHfLock = #{ishflock,jdbcType=TINYINT},",
          "PriceDj = #{pricedj,jdbcType=DECIMAL},",
          "TnPriceDj = #{tnpricedj,jdbcType=DECIMAL},",
          "TotalDj = #{totaldj,jdbcType=DECIMAL},",
          "IsDj2AreaLock = #{isdj2arealock,jdbcType=TINYINT},",
          "IsBzj2AreaLock = #{isbzj2arealock,jdbcType=TINYINT},",
          "IsDjTf = #{isdjtf,jdbcType=TINYINT},",
          "IsBzjTf = #{isbzjtf,jdbcType=TINYINT},",
          "IsDjAreaModify = #{isdjareamodify,jdbcType=TINYINT},",
          "ChooseRoomBookingGUID = #{chooseroombookingguid,jdbcType=CHAR},",
          "Visible = #{visible,jdbcType=INTEGER},",
          "isyl = #{isyl,jdbcType=INTEGER},",
          "roombz = #{roombz,jdbcType=VARCHAR},",
          "PreRoomGUID = #{preroomguid,jdbcType=VARCHAR},",
          "FloorGUID = #{floorguid,jdbcType=CHAR},",
          "UnitGUID = #{unitguid,jdbcType=CHAR},",
          "ResourcesTypeGUID = #{resourcestypeguid,jdbcType=CHAR},",
          "CurRentStatus = #{currentstatus,jdbcType=TINYINT},",
          "RoomStatus = #{roomstatus,jdbcType=TINYINT},",
          "Cg = #{cg,jdbcType=VARCHAR},",
          "Hz = #{hz,jdbcType=VARCHAR},",
          "Power = #{power,jdbcType=VARCHAR},",
          "Gas = #{gas,jdbcType=VARCHAR},",
          "Gs = #{gs,jdbcType=VARCHAR},",
          "Ps = #{ps,jdbcType=VARCHAR},",
          "Kt = #{kt,jdbcType=VARCHAR},",
          "Other = #{other,jdbcType=VARCHAR},",
          "YJQYDate = #{yjqydate,jdbcType=TIMESTAMP},",
          "CreateDate = #{createdate,jdbcType=TIMESTAMP},",
          "IsAlowIn = #{isalowin,jdbcType=TINYINT},",
          "Client = #{client,jdbcType=VARCHAR},",
          "EntrustDate = #{entrustdate,jdbcType=TIMESTAMP},",
          "EntrustJbr = #{entrustjbr,jdbcType=VARCHAR},",
          "EntrustJbDate = #{entrustjbdate,jdbcType=TIMESTAMP},",
          "EntrustEndDate = #{entrustenddate,jdbcType=TIMESTAMP},",
          "Contact = #{contact,jdbcType=VARCHAR},",
          "EntrustJbrGUID = #{entrustjbrguid,jdbcType=CHAR},",
          "RoomInfo = #{roominfo,jdbcType=VARCHAR},",
          "RoomShortInfo = #{roomshortinfo,jdbcType=VARCHAR},",
          "RoomSort = #{roomsort,jdbcType=VARCHAR},",
          "RoomZlBz = #{roomzlbz,jdbcType=VARCHAR},",
          "ERPCode = #{erpcode,jdbcType=VARCHAR},",
          "IsTransferERPCode = #{istransfererpcode,jdbcType=TINYINT},",
          "ERPCodeApproveState = #{erpcodeapprovestate,jdbcType=VARCHAR},",
          "VirtualAccount = #{virtualaccount,jdbcType=VARCHAR},",
          "SaleStatus = #{salestatus,jdbcType=VARCHAR},",
          "ShortUnitNo = #{shortunitno,jdbcType=VARCHAR},",
          "ShortVirtualAccount = #{shortvirtualaccount,jdbcType=VARCHAR}",
        "where RoomGUID = #{roomguid,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(PRoom record);
}